# Generated by Django 5.1.2 on 2024-10-25 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.BigIntegerField(blank=True, error_messages={'unique': 'enter valid phone number'}, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+989123456789'. Up to 10 digits allowed after the country code", regex='^\\+98[0-9]{10}$')], verbose_name='mobile number'),
        ),
    ]
